Robot:
  Number: 2
  InitialPose: 1
  Max_force: 0.8
  Position:
    r1:  # Leader (center)
      x: 10
      y: -10
      z: 1

    r2:  # Follows r1
      x: -10
      y: 10
      z: 2

    r3:  # Follows r1
      x: 1.06
      y: 0.94
      z: 3

    r4:  # Follows r1
      x: -0.01
      y: 1.00
      z: 4

    r5:  # Follows r2
      x: -1.70
      y: 1.80
      z: 5

    r6:  # Follows r2
      x: -0.90
      y: 2.30
      z: 6

    r7:  # Follows r3
      x: 1.80
      y: 1.80
      z: 7

    r8:  # Follows r7
      x: 2.20
      y: 2.80
      z: 8
      
    r9:  # Below-right corner
      x: 5
      y: -15
      z: 1

    r10:  # Mirror of r1 across X-axis
      x: -10
      y: -5
      z: 1


    r11: 
      x: 5
      y: -19
      z: 11

    r12: 
      x: -9
      y: -11
      z: 12
      
    r13:
      x: -4
      y: 15
      z: 13

    r14:
      x: 14
      y: -15
      z: 14

    r15:
      x: 8
      y: 11
      z: 15



    

Control:
  Custom_Control_Law : True # Enable Custom Control
  Position_Control : 0 # Enable Position Control
  Position_params:
    kp: 1.2 # Proportional Gain
    kd: 3.5 # differential Gain
  
  Consensus_Control : False # Enable Consensus Control
  Consensus_params:
    con_kp : 3
    con_kd : 30 
    Communication_Graph : 0 # 0- Full communication(Automatically Generated L-matrix), 1 - User will specify L-matrix
    L_mat : [[3,-1,-1,-1],    # Lagrangian Matrix
             [-1,3,-1,-1],
             [-1,-1,3,-1],
             [-1,-1,-1,3]] 
    Leader : 0 # For leader follower give the index of leader, 0-no-leader only distributed control # Don't select last drone as a leader
    minmax : 0 # Enable for Non-linear Minmax Control , In minmax leader is 1st drone  # Make Leader flag 0 before using minmax


# Please find the plot at location mascot/scripts/figures 
# Plots will be overwrited after each controller program run So please copy it if you need it.
Plots : 
  Position : 1 # Enable for position Plot
  Velocity : 1 # Enable for Velocity Plot
  Save_plot : 1 # Enable to save Plot
  Show_plot : 0 # Enable to show Plot  Plot will be shown when the program is killed with ( Ctrl+C ) Key

